# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-java@v3
       with:
         distribution: 'temurin' # See 'Supported distributions' for available options
         java-version: '17'    
     - name: Grant Permissions to gradlew
       run: chmod +x gradlew
     - name: build gradle project step
       uses: gradle/gradle-build-action@v2
       with:
          arguments: test
     - name: Test
       run: ./gradlew clean test
     - uses: actions/upload-artifact@v3
       if: ${{ failure() }}
       with:
        name: Package
        path: build/reports/tests/test
     - name: Test rerun
       if: ${{ failure() }}
       run: ./gradlew clean test
